import React from 'react'
import type { DocInstance, DocTemplate } from './types'
import { t } from '@/i18n/strings'

type Props = {
  template: DocTemplate
  instance: DocInstance
}

const formatDate = (value: string) => {
  try {
    const date = new Date(value)
    if (Number.isNaN(date.getTime())) return value
    return date.toLocaleString()
  } catch {
    return value
  }
}

const renderValue = (field: DocTemplate['fields'][number], value: any) => {
  switch (field.type) {
    case 'checkbox':
      return value ? t('doc.field.yes', 'Yes') : t('doc.field.no', 'No')
    case 'multiselect':
      return Array.isArray(value) ? value.join(', ') : value || ''
    case 'table': {
      const rows = Array.isArray(value) ? value : []
      const columns = field.columns && field.columns.length > 0
        ? field.columns
        : rows.length > 0
        ? Object.keys(rows[0])
        : []
      return (
        <table className="doc-table">
          <thead>
            <tr>
              {columns.map(column => (
                <th key={column}>{column}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 ? (
              <tr>
                <td colSpan={columns.length || 1} className="doc-empty">
                  {t('doc.table.empty', 'No entries yet')}
                </td>
              </tr>
            ) : (
              rows.map((row, index) => (
                <tr key={index}>
                  {columns.map(column => (
                    <td key={column}>{row?.[column] ?? ''}</td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      )
    }
    case 'date':
      return formatDate(value)
    default:
      return typeof value === 'string' ? value : value ?? ''
  }
}

export default function DocRenderer({ template, instance }: Props) {
  return (
    <div className="doc-renderer">
      <header className="doc-header">
        <div>
          <h1>{template.title}</h1>
          <p className="doc-description">{template.description}</p>
        </div>
        {template.exportable.includes('pdf') && (
          <span className="doc-badge" aria-label={t('doc.badge.exportable', 'Generated by EUCertify')}>
            {t('doc.badge.exportable', 'Generated by EUCertify')}
          </span>
        )}
      </header>
      <section className="doc-meta">
        <div>
          <strong>{t('doc.meta.version', 'Version')}</strong>
          <span>{instance.version}</span>
        </div>
        <div>
          <strong>{t('doc.meta.created', 'Created')}</strong>
          <span>{formatDate(instance.createdAt)}</span>
        </div>
        <div>
          <strong>{t('doc.meta.updated', 'Updated')}</strong>
          <span>{formatDate(instance.updatedAt)}</span>
        </div>
        <div>
          <strong>{t('doc.meta.status', 'Status')}</strong>
          <span>{instance.status}</span>
        </div>
      </section>

      <section className="doc-fields">
        {template.fields.map(field => (
          <article className="doc-field" key={field.key}>
            <header>
              <h2>{field.label}</h2>
              {field.help ? <small>{field.help}</small> : null}
            </header>
            <div className="doc-value">{renderValue(field, instance.data[field.key])}</div>
          </article>
        ))}
      </section>

      {template.footerNotes?.length ? (
        <footer className="doc-footer">
          <h3>{t('doc.footer.notes', 'Notes')}</h3>
          <ul>
            {template.footerNotes.map(note => (
              <li key={note}>{note}</li>
            ))}
          </ul>
        </footer>
      ) : null}
    </div>
  )
}
