const STRINGS: Record<string, string> = {
  'doc.badge.exportable': 'Generated by EUCertify',
  'doc.meta.version': 'Version',
  'doc.meta.created': 'Created',
  'doc.meta.updated': 'Updated',
  'doc.meta.status': 'Status',
  'doc.field.yes': 'Yes',
  'doc.field.no': 'No',
  'doc.table.empty': 'No entries yet',
  'doc.footer.notes': 'Notes',
  'docs.create.heading': 'Create document',
  'docs.create.description': 'Generate compliance documentation directly from your answers.',
  'docs.actions.save': 'Save draft',
  'docs.actions.create': 'Create draft',
  'docs.actions.exportPdf': 'Export PDF',
  'docs.actions.exportDocx': 'Export DOCX',
  'docs.table.addRow': 'Add row',
  'docs.table.remove': 'Remove',
  'docs.empty': 'No documents yet',
  'docs.status.exportable': '🟢 Generated by EUCertify',
  'docs.status.upload': '🟡 Upload evidence',
  'docs.status.external': '🔴 External requirement'
}

export function t(key: string, def?: string): string {
  return STRINGS[key] ?? def ?? key
}

export default STRINGS
