export interface DoCData {
  manufacturerName: string;
  manufacturerAddress: string;
  productName: string;
  productModel?: string;
  productDescription?: string;
  laws: { id: string; type: "Directive" | "Regulation" }[];
  standards: { id: string; title: string }[];
  place?: string;
  dateISO: string;
  signatoryName?: string;
  signatoryTitle?: string;
  signatureText?: string;
  version?: string;
  createdAt?: string;
  updatedAt?: string;
  status?: string;
}

export function renderDoCClassic(d: DoCData, locale: "de" | "en" = "de"): string {
  const L = locale === "de" ? {
    docTitle: "EU-Konformitätserklärung",
    generatedBy: "Erstellt von EUCertify",
    version: "Version",
    created: "Erstellt",
    updated: "Aktualisiert",
    status: "Status",
    manufacturerName: "Herstellername",
    manufacturerAddress: "Herstelleranschrift",
    productName: "Produktbezeichnung",
    modelType: "Modell / Typ",
    applicableLaw: "Anwendbare EU-Rechtsvorschriften",
    id: "ID",
    type: "Art",
    directive: "Richtlinie",
    regulation: "Verordnung",
    standardsApplied: "Angewandte Normen",
    enStandard: "EN-Norm",
    title: "Titel",
    placeDate: "Ort & Datum der Erklärung",
    signatory: "Name und Funktion des Unterzeichners",
    signature: "Unterschrift",
    signatureNote: "Getippter Name ist für Entwurf zulässig.",
    notes: "Hinweise",
    notesList: [
      "Diese Erklärung gilt für das oben beschriebene Produkt und die aufgeführten Rechtsvorschriften.",
      "Die unterzeichnete DoC wird mit der Technischen Dokumentation 10 Jahre aufbewahrt."
    ]
  } : {
    docTitle: "EU Declaration of Conformity",
    generatedBy: "Generated by EUCertify",
    version: "Version",
    created: "Created",
    updated: "Updated",
    status: "Status",
    manufacturerName: "Manufacturer Name",
    manufacturerAddress: "Manufacturer Address",
    productName: "Product Name/Description",
    modelType: "Model / Type",
    applicableLaw: "Applicable EU Legislation",
    id: "ID",
    type: "Type",
    directive: "Directive",
    regulation: "Regulation",
    standardsApplied: "Standards Applied",
    enStandard: "EN Standard",
    title: "Title",
    placeDate: "Place & Date of Declaration",
    signatory: "Name and Title of signatory",
    signature: "Signature",
    signatureNote: "Typed name is acceptable for draft.",
    notes: "Notes",
    notesList: [
      "This DoC covers the product as described and listed legislation.",
      "Keep the signed DoC with the Technical File for 10 years."
    ]
  };

  const esc = (s: string = "") => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]!));
  const lines = (s: string = "") => esc(s).replace(/\n/g, "<br/>");
  const lawType = (t: DoCData["laws"][number]["type"]) => t === "Regulation" ? L.regulation : L.directive;

  const css = `
  body{margin:0;background:#f6f7f9;}
  .doc{font-family:ui-sans-serif,system-ui,Segoe UI,Roboto,Arial,sans-serif;color:#111;line-height:1.45;padding:18px}
  .card{background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden}
  .header{display:flex;justify-content:space-between;align-items:flex-start;padding:16px 16px 0 16px}
  .title{font-size:20px;font-weight:700;margin:0}
  .badge{background:#e6f2ff;color:#007aff;border-radius:16px;padding:6px 10px;font-size:12px}
  .meta{display:flex;gap:24px;font-size:12px;color:#555;padding:4px 16px 12px}
  .row{padding:12px 16px;border-top:1px solid #edf0f4}
  .label{font-weight:700;margin-bottom:6px}
  .box{background:#f5f7fb;border:1px solid #edf0f4;border-radius:6px;padding:10px;white-space:pre-wrap}
  table{width:100%;border-collapse:collapse;margin-top:6px;border:1px solid #dbe3f0}
  thead th{background:#0a84ff;color:#fff;text-align:left;padding:8px;font-weight:700;font-size:13px}
  tbody td{border-top:1px solid #e6edf7;padding:8px;font-size:13px}
  .notes{font-size:12px;color:#444}
  `;

  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>${esc(L.docTitle)}</title>
  <style>${css}</style></head><body><div class="doc">
    <div class="card">
      <div class="header">
        <h1 class="title">${esc(L.docTitle)}</h1>
        <div class="badge">${esc(L.generatedBy)}</div>
      </div>
      <div class="meta">
        <div><strong>${esc(L.version)}</strong><div>${esc(d.version ?? "1")}</div></div>
        ${d.createdAt ? `<div><strong>${esc(L.created)}</strong><div>${esc(d.createdAt!)}</div></div>` : ""}
        ${d.updatedAt ? `<div><strong>${esc(L.updated)}</strong><div>${esc(d.updatedAt!)}</div></div>` : ""}
        ${d.status ? `<div><strong>${esc(L.status)}</strong><div>${esc(d.status!)}</div></div>` : ""}
      </div>

      <div class="row">
        <div class="label">${esc(L.manufacturerName)}</div>
        <div class="box">${esc(d.manufacturerName || "")}</div>
      </div>

      <div class="row">
        <div class="label">${esc(L.manufacturerAddress)}</div>
        <div class="box">${lines(d.manufacturerAddress || "")}</div>
      </div>

      <div class="row">
        <div class="label">${esc(L.productName)}</div>
        <div class="box">${esc(d.productName || "")}</div>
      </div>

      <div class="row">
        <div class="label">${esc(L.modelType)}</div>
        <div class="box">${esc(d.productModel || "")}</div>
      </div>

      <div class="row">
        <div class="label">${esc(L.applicableLaw)}</div>
        <table><thead><tr>
          <th style="width:30%">${esc(L.id)}</th><th>${esc(L.type)}</th>
        </tr></thead><tbody>
          ${(d.laws||[]).map(l=>`<tr><td>${esc(l.id)}</td><td>${esc(lawType(l.type))}</td></tr>`).join("")}
        </tbody></table>
      </div>

      <div class="row">
        <div class="label">${esc(L.standardsApplied)}</div>
        <table><thead><tr>
          <th style="width:30%">${esc(L.enStandard)}</th><th>${esc(L.title)}</th>
        </tr></thead><tbody>
          ${(d.standards||[]).map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.title)}</td></tr>`).join("")}
        </tbody></table>
      </div>

      <div class="row">
        <div class="label">${esc(L.placeDate)}</div>
        <div class="box">${esc(d.place || "")} ${d.dateISO ? (" – " + esc(d.dateISO)) : ""}</div>
      </div>

      <div class="row">
        <div class="label">${esc(L.signatory)}</div>
        <div class="box">${esc(d.signatoryName || "")}${d.signatoryTitle ? (" – " + esc(d.signatoryTitle)) : ""}</div>
      </div>

      <div class="row">
        <div class="label">${esc(L.signature)}</div>
        <div class="box">${esc(d.signatureText || (locale === "de" ? "Max Mustermann" : "John Doe"))}
          <span style="float:right;color:#777;font-size:12px">${esc(L.signatureNote)}</span>
        </div>
      </div>

      <div class="row notes">
        <div class="label">${esc(L.notes)}</div>
        <ul>${L.notesList.map(n=>`<li>${esc(n)}</li>`).join("")}</ul>
      </div>
    </div>
  </div></body></html>`;
}
