import type { DocData } from '@/utils/docData'

type Props = {
  data: DocData
}

export default function EUDeclarationA4({ data }: Props) {
  return (
    <div id="doc-a4" className="doc-a4">
      <header className="doc-header">
        <div>
          <p className="doc-subtitle">EU-Verordnung 2014/53/EU</p>
          <h1>EU-Konformitätserklärung</h1>
          <p className="doc-subtitle">European Union Declaration of Conformity</p>
        </div>
        <div className="doc-meta">
          <p>Produkt: {data.productName}</p>
          <p>Modell/Typ: {data.productModel}</p>
        </div>
      </header>

      <section className="doc-section">
        <h2>1. Hersteller</h2>
        <table>
          <tbody>
            <tr>
              <th>Name</th>
              <td>{data.manufacturerName}</td>
            </tr>
            <tr>
              <th>Anschrift</th>
              <td>
                <pre>{data.manufacturerAddress}</pre>
              </td>
            </tr>
          </tbody>
        </table>
      </section>

      <section className="doc-section">
        <h2>2. Produktbeschreibung</h2>
        <table>
          <tbody>
            <tr>
              <th>Produktname</th>
              <td>{data.productName}</td>
            </tr>
            <tr>
              <th>Modell/Typ</th>
              <td>{data.productModel}</td>
            </tr>
            <tr>
              <th>Ermittelte Merkmale</th>
              <td>{data.derived_tags.length ? data.derived_tags.join(', ') : '—'}</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section className="doc-section">
        <h2>3. Angewandte EU-Richtlinien</h2>
        <table>
          <tbody>
            {data.laws.length ? (
              data.laws.map(law => (
                <tr key={law}>
                  <td>{law}</td>
                </tr>
              ))
            ) : (
              <tr>
                <td>Keine Richtlinien ausgewählt</td>
              </tr>
            )}
          </tbody>
        </table>
      </section>

      <section className="doc-section">
        <h2>4. Harmonisierte EN-Normen</h2>
        <table>
          <tbody>
            {data.standards.length ? (
              data.standards.map(standard => (
                <tr key={standard}>
                  <td>{standard}</td>
                </tr>
              ))
            ) : (
              <tr>
                <td>Keine Normen ausgewählt</td>
              </tr>
            )}
          </tbody>
        </table>
      </section>

      <section className="doc-section">
        <h2>5. Unterzeichnung</h2>
        <table>
          <tbody>
            <tr>
              <th>Ort</th>
              <td>{data.declarationPlace}</td>
            </tr>
            <tr>
              <th>Datum</th>
              <td>{data.declarationDate}</td>
            </tr>
            <tr>
              <th>Name</th>
              <td>{data.signatoryName}</td>
            </tr>
            <tr>
              <th>Position</th>
              <td>{data.signatoryTitle}</td>
            </tr>
            <tr>
              <th>Unterschrift</th>
              <td>{data.signatorySignature}</td>
            </tr>
          </tbody>
        </table>
      </section>

      <div className="doc-badge">Generated by EUCertify</div>
    </div>
  )
}
